apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: postgres
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS jenkins_log (
      id SERIAL PRIMARY KEY,
      executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
