apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_USER: jenkins
  POSTGRES_DB: jenkins_db

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  password: cG9zdGdyZXM=  # base64 for "postgres"
  postgres-password: cG9zdGdyZXM=  # optional; include both if needed

